<a href="https://colab.research.google.com/github/vodnalasricharan/Ineuron/blob/master/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
'''Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.'''
def Vandermonde(inputvector,outputdimensions,increasing=False):
  if increasing:
    output_array = np.array([x**(outputdimensions-1-i) for x in inputvector for i in range(outputdimensions)]).reshape(inputvector.size,outputdimensions)
  else:
    output_array = np.array([x**i for x in inputvector for i in range(outputdimensions)]).reshape(inputvector.size,outputdimensions)
  return output_array

inputvector = np.array([44,17,37,16,13])
n= 6
ouput_array_dec= Vandermonde(inputvector,n,False)
output_array_inc = Vandermonde(inputvector,n,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",n,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",ouput_array_dec,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_array_inc,"\n")

The input array is: [44 17 37 16 13] 

Number of columns in output matrix should be: 6 

Vander matrix of the input array in decreasing order of powers:

 [[        1        44      1936     85184   3748096 164916224]
 [        1        17       289      4913     83521   1419857]
 [        1        37      1369     50653   1874161  69343957]
 [        1        16       256      4096     65536   1048576]
 [        1        13       169      2197     28561    371293]] 

Vander matrix of the input array in increasing order of powers:

 [[164916224   3748096     85184      1936        44         1]
 [  1419857     83521      4913       289        17         1]
 [ 69343957   1874161     50653      1369        37         1]
 [  1048576     65536      4096       256        16         1]
 [   371293     28561      2197       169        13         1]] 



In [10]:
'''Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.'''



def moving_avrg(input_array,k):
  return np.array([np.mean(input_array[i:i+k])for i in range(input_array.size-k+1)])


In [11]:

'''Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.'''

inp=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
moving_avrg(inp,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])